version: "3.3"
services:
  database:
    image: postgres
    volumes:
      - ./test_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=icm
    ports:
      - 5432:5432
  cache:
    image: redis
    ports:
      - 6379:6379