version: "3.3"
services:
  database:
    image: postgres
    volumes:
      - ./test_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=icm
  cache:
    image: redis
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 8000:8000
    env_file:
      - ./test_data/config.env
    depends_on:
      - database
      - cache