version: "3.3"
services:
  database:
    image: postgres
    volumes:
      - ./test-data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=server
  cache:
    image: redis
  server:
    build: .
    ports:
      - 8080:8085
    env_file:
      - ./conf/config.env
    depends_on:
      - database
      - cache