name: Bump version
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        id: tag_test
        run: |
          echo ${{steps.tag_version.outputs.new_tag}}
          gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
          gh release create ${{steps.tag_version.outputs.new_tag}}
